### ISSUE TITLE
Cambiar a Expo

### ISSUE THREAD

**Issue by yeguacelestial** [yeguacelestial/uanlove#1]
Es mejor idea iniciar el proyecto con Expo. 

En caso de que sea necesario, se puede hacer eject del codigo para tener la estructura como la que tenemos ahorita.

**Comment by yeguacelestial** [comment]
@MauHylian @Canciller

**Comment by Canciller** [comment]
Listo @yeguacelestial 💋

**Comment by MauHylian** [comment]
Excelente, vamos bien!
